version: '3.8'

services:
  ingester:
    build:
      context: ./go-service
      dockerfile: Dockerfile
    command: ["./ingester"]
    environment:
      - API_ENDPOINT=${API_ENDPOINT}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - DATASET=${DATASET}
      - RAW_TABLE=${RAW_TABLE}
      - SOURCE=${SOURCE}
      - FETCH_INTERVAL=${FETCH_INTERVAL}
    volumes:
      - ./service-account.json:/app/service-account.json
    env_file:
      - .env

  api:
    build:
      context: ./go-service
      dockerfile: Dockerfile
    command: ["./api"]
    ports:
      - "8080:8080"
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - DATASET=${DATASET}
      - PROD_TABLE=${PROD_TABLE}
      - PORT=8080
    volumes:
      - ./service-account.json:/app/service-account.json
    env_file:
      - .env

  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    environment:
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - DATASET=${DATASET}
    volumes:
      - ./service-account.json:/app/service-account.json
    env_file:
      - .env