data_ingestion:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID', 'project-id') }}"
      dataset: "{{ env_var('DATASET', 'data_ingestion') }}"
      keyfile: "../service-account.json"
      threads: 4
      timeout_seconds: 300
      location: US
      priority: interactive